### ISSUE TITLE
Cannot open UI with 209-1 build

### ISSUE THREAD

**Issue by gyliu513** [instana/lab-self-hosting-k8s#14]
After install with automation script with 209-1, UI cannot be opened.

@morningspace ^^

![image](https://user-images.githubusercontent.com/4461983/137106586-2205eb7d-b946-4146-b9e8-ccf4d09fe82b.png)

**Comment by morningspace** [comment]
I just tried and it looks the env in. issue has been recovered. I can see the UI and login successfully. @gyliu513
